import { Text, cardStyle } from "@/components/ui"
import { spacing } from "@/theme"
import { useMemo, useState } from "react"
import { StyleSheet, View } from "react-native"
import { useUlbWards } from "../hooks/queries"
import { digitsOnly, parcelNumberError, parseConstructedYear, unitNumberError } from "../lib/field-format"
import { propertyIdPreview } from "../lib/property-identity"
import { sortWardsByNumber } from "../lib/ward-order"
import type { SurveyEditableFields, SurveyPatch, SurveyRecord, WardOption } from "../types"
import { OutlinedField } from "./outlined-field"
import { SlumChoice } from "./slum-choice"
import { WardDropdown } from "./ward-dropdown"

const BASE_ID_CAPTION = "Base ID fills in here; property-use suffix is added on the taxation step."
const FULL_ID_CAPTION = "Generated by the server from ULB, ward, parcel, unit, and property use. Read-only."

type Props = {
  record: SurveyRecord
  fields: SurveyEditableFields
  editable: boolean
  setFields: (patch: SurveyPatch) => void
}

function wardLabel(ward: Pick<WardOption, "wardNumber" | "wardName" | "kind">): string {
  if (ward.kind === "ZERO") return `ZERO · ${ward.wardName}`
  return `${ward.wardNumber} · ${ward.wardName}`
}

function SectionTitle({ children }: { children: string }) {
  return (
    <Text variant="label" tone="secondary" style={styles.sectionTitle}>
      {children}
    </Text>
  )
}

/**
 * Property step: ULB, ward, sector, parcel, unit, year, old number, Property ID, and slum.
 * Ownership, property use, and property type are collected on Taxation.
 */
export function PropertyStep({ record, fields, editable, setFields }: Props) {
  const wardsQuery = useUlbWards(record.ulbId)
  const [yearText, setYearText] = useState<string | null>(null)
  const [yearError, setYearError] = useState<string | undefined>()
  const wards = useMemo(() => sortWardsByNumber(wardsQuery.data?.items ?? []), [wardsQuery.data?.items])
  const selected = wards.find((ward) => ward.id === fields.wardId) ?? null
  const currentWard = selected
    ? { wardNumber: selected.wardNumber, kind: selected.kind ?? null }
    : fields.wardId === record.wardId
      ? record.ward
      : null
  const identity = propertyIdPreview({
    ulbCode: record.ulbCode ?? record.ulb?.code,
    currentWard,
    originalWard: record.originalWard,
    storedWardNumber: record.wardNumber,
    parcelNo: fields.parcelNumber,
    unitNo: fields.unitSubNo,
    propertyUse: fields.propertyUse,
  })
  const parcelError = parcelNumberError(fields.parcelNumber)
  const unitError = unitNumberError(fields.unitSubNo)
  const wardOptions = useMemo(() => {
    const options = wards.map((ward) => ({ value: ward.id, label: wardLabel(ward) }))
    if (fields.wardId && record.ward && !options.some((option) => option.value === fields.wardId)) {
      options.unshift({ value: record.ward.id, label: wardLabel(record.ward) })
    }
    return options
  }, [fields.wardId, record.ward, wards])
  const ulbLine = [record.ulb?.code, record.district?.name].filter((part) => part && part.trim() !== "").join(" · ")
  const yearValue = yearText ?? (fields.constructedYear === null ? "" : String(fields.constructedYear))
  const commitYear = (raw: string) => {
    setYearText(raw)
    const parsed = parseConstructedYear(raw)
    if (parsed.pending) {
      setYearError(undefined)
      return
    }
    setYearError(parsed.error)
    if (parsed.error) return
    setFields({ constructedYear: parsed.year })
  }
  return (
    <View style={styles.stack}>
      <View style={[cardStyle, styles.ulbCard]}>
        <SectionTitle>ULB</SectionTitle>
        <Text variant="bodyStrong">{record.ulb?.name ?? "—"}</Text>
        {ulbLine ? (
          <Text variant="caption" tone="secondary">
            {ulbLine}
          </Text>
        ) : null}
      </View>
      <View style={styles.block}>
        <WardDropdown
          options={wardOptions}
          value={fields.wardId || null}
          disabled={!editable || wardOptions.length === 0}
          onChange={(wardId) => setFields({ wardId })}
        />
        {selected ? (
          <Text variant="caption" tone="secondary">
            {selected.wardName}
          </Text>
        ) : null}
      </View>
      <OutlinedField
        label="Sector number"
        value={fields.sectorNo ?? ""}
        editable={editable}
        keyboard="number-pad"
        placeholder="e.g. 3"
        helper="Optional — municipal sector within the ward"
        onChangeText={
          editable
            ? (raw) => {
              const digits = digitsOnly(raw)
              setFields({ sectorNo: digits === "" ? null : digits })
            }
            : undefined
        }
      />
      <SectionTitle>Identification</SectionTitle>
      <View style={styles.row}>
        <OutlinedField
          label="Parcel number"
          required
          value={fields.parcelNumber ?? ""}
          editable={editable}
          keyboard="number-pad"
          maxLength={5}
          error={fields.parcelNumber ? parcelError : undefined}
          onChangeText={
            editable
              ? (raw) => {
                const digits = digitsOnly(raw)
                setFields({ parcelNumber: digits === "" ? null : digits })
              }
              : undefined
          }
        />
        <OutlinedField
          label="Unit number"
          required
          value={fields.unitSubNo ?? ""}
          editable={editable}
          keyboard="number-pad"
          maxLength={3}
          error={fields.unitSubNo ? unitError : undefined}
          onChangeText={
            editable
              ? (raw) => {
                const digits = digitsOnly(raw)
                setFields({ unitSubNo: digits === "" ? null : digits })
              }
              : undefined
          }
        />
      </View>
      <SectionTitle>Additional details (optional)</SectionTitle>
      <OutlinedField
        label="Constructed year"
        value={yearValue}
        editable={editable}
        keyboard="number-pad"
        maxLength={4}
        placeholder="e.g. 1998"
        helper="Year the structure was built (1800–present)"
        error={yearError}
        onChangeText={editable ? commitYear : undefined}
      />
      <OutlinedField
        label="Old property number"
        value={fields.propertyIdOld ?? ""}
        editable={editable}
        placeholder="e.g. 12/45/A"
        helper="Previous assessment register number"
        onChangeText={
          editable
            ? (raw) => {
              const trimmed = raw.trim()
              setFields({ propertyIdOld: trimmed === "" ? null : trimmed })
            }
            : undefined
        }
      />
      <OutlinedField
        label="Property ID"
        value={identity.value ?? ""}
        editable={false}
        placeholder="Auto-generated from ward, parcel, and unit"
        helper={identity.isComplete ? FULL_ID_CAPTION : BASE_ID_CAPTION}
      />
      <View style={[cardStyle, styles.slumCard]}>
        <SectionTitle>Slum classification</SectionTitle>
        <Text variant="caption" tone="secondary">
          Indicates whether the property falls within a notified slum area.
        </Text>
        <SlumChoice value={fields.isSlum} disabled={!editable} onChange={(isSlum) => setFields({ isSlum })} />
      </View>
    </View>
  )
}

const styles = StyleSheet.create({
  stack: { gap: spacing.lg },
  block: { gap: spacing.xs },
  row: { flexDirection: "row", gap: spacing.md, alignItems: "flex-start" },
  ulbCard: { gap: spacing.xs, padding: spacing.lg },
  slumCard: { gap: spacing.sm, padding: spacing.lg },
  sectionTitle: { letterSpacing: 0.4, textTransform: "uppercase" },
})
