import { Text, cardStyle } from "@/components/ui"
import { colors, spacing } from "@/theme"
import type { ReactNode } from "react"
import { Pressable, StyleSheet, View } from "react-native"
import { optionLabel } from "../lib/labels"
import { previewPropertyId } from "../lib/property-identity"
import type { StepId, SurveySnapshot } from "../lib/requirements"
import type { SurveyRecord } from "../types"
import { SurveyLocationMap } from "./SurveyLocationMap"

function display(value: string | number | boolean | null | undefined): string {
  if (value === null || value === undefined) return "—"
  if (typeof value === "boolean") return value ? "Yes" : "No"
  if (typeof value === "number") return String(value)
  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : "—"
}

function labeled(value: string | null | undefined): string {
  return value ? optionLabel(value) : "—"
}

function toCoord(value: SurveySnapshot["latitude"]): number | null {
  if (value === null) return null
  const n = typeof value === "number" ? value : Number(value)
  return Number.isFinite(n) ? n : null
}

export function ReviewSection({
  snapshot,
  record,
  editable,
  onEdit,
}: {
  snapshot: SurveySnapshot
  record: SurveyRecord
  editable: boolean
  onEdit: (step: StepId) => void
}) {
  const edit = editable ? onEdit : undefined
  const lat = toCoord(snapshot.latitude)
  const lng = toCoord(snapshot.longitude)
  const builtUp = record.floors.reduce((sum, floor) => {
    if (floor.areaSqFt === null) return sum
    const n = typeof floor.areaSqFt === "number" ? floor.areaSqFt : Number(floor.areaSqFt)
    return sum + (Number.isFinite(n) ? n : 0)
  }, 0)
  const hasFront = snapshot.uploadedPhotoTypes.includes("FRONT")
  const hasSide = snapshot.uploadedPhotoTypes.includes("SIDE")
  const propertyIdPreview = previewPropertyId({
    ulbCode: record.ulbCode ?? record.ulb?.code,
    wardNo: record.ward?.wardNumber,
    currentWard: record.ward,
    originalWard: record.originalWard,
    storedWardNumber: record.wardNumber,
    parcelNo: snapshot.parcelNumber,
    unitNo: snapshot.unitSubNo,
    propertyUse: snapshot.propertyUse,
  })
  const propertyIdShown =
    propertyIdPreview ?? "Will be generated after parcel, unit and property use are completed."

  return (
    <View style={styles.stack}>
      <View style={[cardStyle, styles.card]}>
        <Text variant="heading">Review & submit</Text>
        <Text variant="body" tone="secondary">
          Confirm each section, then submit for review.
        </Text>
      </View>
      <ReviewCard title="Survey" onEdit={edit ? () => edit("start") : undefined}>
        <Line label="Assessment year" value={labeled(snapshot.assessmentYear)} />
        <Line label="District" value={display(record.district?.name)} />
        <Line label="ULB" value={display(record.ulb?.name)} />
        <Line label="Ward" value={display(snapshot.wardLabel)} />
      </ReviewCard>
      <ReviewCard title="Property" onEdit={edit ? () => edit("property") : undefined}>
        <Line label="Parcel number" value={display(snapshot.parcelNumber)} />
        <Line label="Unit number" value={display(snapshot.unitSubNo)} />
        <Line label="Property ID" value={propertyIdShown} />
        <Text variant="caption" tone="secondary">
          {propertyIdPreview ? "Generated by server. Read-only." : "Property ID is assigned by the server. It cannot be edited."}
        </Text>
        <Line label="Property type" value={labeled(snapshot.propertyType)} />
        <Line label="Property use" value={labeled(snapshot.propertyUse)} />
        <Line label="Ownership type" value={labeled(snapshot.ownershipType)} />
      </ReviewCard>
      <ReviewCard title="Owner" onEdit={edit ? () => edit("owner") : undefined}>
        <Line label="Respondent" value={display(snapshot.respondentName)} />
        <Line label="Relationship" value={display(snapshot.relationshipWithOwner)} />
        <Line label="Mobile" value={display(snapshot.mobileNumber)} />
        <Line label="Co-owners" value={String(snapshot.coOwnerCount)} />
      </ReviewCard>
      <ReviewCard title="Address" onEdit={edit ? () => edit("address") : undefined}>
        <Line label="House number" value={display(snapshot.houseDoorNo)} />
        <Line label="Locality" value={display(snapshot.locality)} />
        <Line label="Colony" value={display(snapshot.colony)} />
        <Line label="PIN code" value={display(snapshot.pinCode)} />
      </ReviewCard>
      <ReviewCard title="Taxation" onEdit={edit ? () => edit("taxation") : undefined}>
        <Line label="Situation" value={labeled(snapshot.situation)} />
        <Line label="Road type" value={labeled(snapshot.roadType)} />
        <Line label="Road size tax zone" value={labeled(snapshot.taxRateZone)} />
      </ReviewCard>
      <ReviewCard title="Area" onEdit={edit ? () => edit("area") : undefined}>
        <Line label="Plot area" value={snapshot.plotAreaSqFt === null ? "—" : `${String(snapshot.plotAreaSqFt)} sq ft`} />
        <Line label="Plinth area" value={snapshot.plinthAreaSqFt === null ? "—" : `${String(snapshot.plinthAreaSqFt)} sq ft`} />
        <Line label="Total built-up area" value={record.floors.length ? `${builtUp} sq ft` : "—"} />
        <Line label="Floors" value={String(snapshot.floorCount)} />
      </ReviewCard>
      <ReviewCard title="Services" onEdit={edit ? () => edit("services") : undefined}>
        <Line label="Water connection" value={labeled(snapshot.waterConnection)} />
        <Line label="Source of water" value={labeled(snapshot.sourceOfWater)} />
        <Line label="Sanitation" value={labeled(snapshot.sanitationType)} />
        <Line label="Door-to-door collection" value={display(snapshot.solidWasteCollection)} />
      </ReviewCard>
      <ReviewCard title="GPS" onEdit={edit ? () => edit("gps") : undefined}>
        {lat !== null && lng !== null ? <SurveyLocationMap latitude={lat} longitude={lng} /> : null}
        <Line label="Latitude" value={lat !== null ? lat.toFixed(6) : "—"} />
        <Line label="Longitude" value={lng !== null ? lng.toFixed(6) : "—"} />
      </ReviewCard>
      <ReviewCard title="Photos" onEdit={edit ? () => edit("photos") : undefined}>
        <Line label="Front view" value={hasFront ? "Added" : "Front photo is required."} />
        <Line label="Side view" value={hasSide ? "Added" : "Side photo is required."} />
      </ReviewCard>
    </View>
  )
}

function ReviewCard({
  title,
  onEdit,
  children,
}: {
  title: string
  onEdit?: () => void
  children: ReactNode
}) {
  return (
    <View style={[cardStyle, styles.card]}>
      <View style={styles.cardHeader}>
        <Text variant="label">{title}</Text>
        {onEdit ? (
          <Pressable accessibilityRole="button" accessibilityLabel={`Edit ${title}`} onPress={onEdit} hitSlop={8}>
            <Text variant="label" tone="primary">
              Edit
            </Text>
          </Pressable>
        ) : null}
      </View>
      {children}
    </View>
  )
}

function Line({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.line}>
      <Text variant="caption" tone="secondary">
        {label}
      </Text>
      <Text variant="bodyStrong">{value}</Text>
    </View>
  )
}

const styles = StyleSheet.create({
  stack: { gap: spacing.md, marginBottom: spacing.lg },
  card: { gap: spacing.sm },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  line: {
    gap: 2,
    paddingVertical: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
})
