import { Text, cardStyle } from "@/components/ui"
import { colors, spacing } from "@/theme"
import type { ReactNode } from "react"
import { Pressable, StyleSheet, View } from "react-native"
import { summarizeAreas } from "../lib/area-summary"
import { gpsFreshnessWarning } from "../lib/gps-freshness"
import { optionLabel } from "../lib/labels"
import { sortOwners } from "../lib/owner-mapping"
import { displayPropertyId, propertyIdPreview } from "../lib/property-identity"
import type { StepId, SurveySnapshot } from "../lib/requirements"
import type { SurveyRecord } from "../types"
import { SurveyLocationMap } from "./SurveyLocationMap"

function display(value: string | number | boolean | null | undefined): string {
  if (value === null || value === undefined) return "—"
  if (typeof value === "boolean") return value ? "Yes" : "No"
  if (typeof value === "number") return String(value)
  const trimmed = value.trim()
  return trimmed.length > 0 ? trimmed : "—"
}

function labeled(value: string | null | undefined): string {
  return value ? optionLabel(value) : "—"
}

function toCoord(value: SurveySnapshot["latitude"]): number | null {
  if (value === null) return null
  const n = typeof value === "number" ? value : Number(value)
  return Number.isFinite(n) ? n : null
}

export function ReviewSection({
  snapshot,
  record,
  editable,
  onEdit,
}: {
  snapshot: SurveySnapshot
  record: SurveyRecord
  editable: boolean
  onEdit: (step: StepId) => void
}) {
  const edit = editable ? onEdit : undefined
  const lat = toCoord(snapshot.latitude)
  const lng = toCoord(snapshot.longitude)
  const accuracy = toCoord(snapshot.gpsAccuracyMeters)
  const areas = summarizeAreas(snapshot.propertyUse, record.floors)
  const owners = sortOwners(record.coOwners)
  const hasFront = snapshot.uploadedPhotoTypes.includes("FRONT")
  const hasSide = snapshot.uploadedPhotoTypes.includes("SIDE")
  const hasInside = snapshot.uploadedPhotoTypes.includes("INSIDE")
  const hasDocument = snapshot.uploadedPhotoTypes.includes("DOCUMENT")
  const freshness = gpsFreshnessWarning(snapshot.capturedAt)
  const identity = propertyIdPreview({
    ulbCode: record.ulbCode ?? record.ulb?.code,
    wardNo: record.ward?.wardNumber,
    currentWard: record.ward,
    originalWard: record.originalWard,
    storedWardNumber: record.wardNumber,
    parcelNo: snapshot.parcelNumber,
    unitNo: snapshot.unitSubNo,
    propertyUse: snapshot.propertyUse,
  })
  const propertyIdShown = displayPropertyId(identity)

  return (
    <View style={styles.stack}>
      <View style={[cardStyle, styles.card]}>
        <Text variant="heading">Review & submit</Text>
        <Text variant="body" tone="secondary">
          Confirm each section, then submit for review.
        </Text>
      </View>
      <ReviewCard title="Survey" onEdit={edit ? () => edit("start") : undefined}>
        <Line label="Assessment year" value={labeled(snapshot.assessmentYear)} />
        <Line label="District" value={display(record.district?.name)} />
        <Line label="ULB" value={display(record.ulb?.name)} />
        <Line label="Ward" value={display(snapshot.wardLabel)} />
      </ReviewCard>
      <ReviewCard title="Property" onEdit={edit ? () => edit("property") : undefined}>
        <Line label="Sector number" value={display(snapshot.sectorNo)} />
        <Line label="Parcel number" value={display(snapshot.parcelNumber)} />
        <Line label="Unit number" value={display(snapshot.unitSubNo)} />
        <Line label="Constructed year" value={display(snapshot.constructedYear)} />
        <Line label="Old property number" value={display(snapshot.propertyIdOld)} />
        <Line label="Property ID" value={propertyIdShown} />
        <Text variant="caption" tone="secondary">
          {identity.isComplete ? "Generated by the server. Read-only." : "Property ID pending until parcel, unit, and property use are complete."}
        </Text>
        <Line label="Slum area" value={snapshot.isSlum ? "Slum area" : "Not in slum area"} />
      </ReviewCard>
      <ReviewCard title="Owner" onEdit={edit ? () => edit("owner") : undefined}>
        <Line label="Respondent" value={display(snapshot.respondentName)} />
        <Line label="Relationship" value={display(snapshot.relationshipWithOwner)} />
        <Line label="Family members" value={display(snapshot.familySize)} />
        {owners.length === 0 ? <Line label="Owner 1" value="—" /> : null}
        {owners.map((owner, index) => (
          <Line
            key={owner.id}
            label={`Owner ${index + 1}`}
            value={[owner.name, owner.fatherOrHusbandName, owner.mobile, owner.alternateMobile].filter(Boolean).join(" · ") || "—"}
          />
        ))}
      </ReviewCard>
      <ReviewCard title="Address" onEdit={edit ? () => edit("address") : undefined}>
        <Line label="District" value={display(record.district?.name)} />
        <Line label="City / Town (ULB)" value={display(record.ulb?.name)} />
        <Line label="House number" value={display(snapshot.houseDoorNo)} />
        <Line label="Locality" value={display(snapshot.locality)} />
        <Line label="Colony" value={display(snapshot.colony)} />
        <Line label="PIN code" value={display(snapshot.pinCode)} />
      </ReviewCard>
      <ReviewCard title="Taxation" onEdit={edit ? () => edit("taxation") : undefined}>
        <Line label="Ownership type" value={labeled(snapshot.ownershipType)} />
        <Line label="Property use" value={labeled(snapshot.propertyUse)} />
        <Line label="Property type" value={labeled(snapshot.propertyType)} />
        <Line label="Situation" value={labeled(snapshot.situation)} />
        <Line label="Road type" value={labeled(snapshot.roadType)} />
        <Line label="Road size tax zone" value={labeled(snapshot.taxRateZone)} />
      </ReviewCard>
      <ReviewCard title="Area" onEdit={edit ? () => edit("area") : undefined}>
        <Line label="Plot area" value={snapshot.plotAreaSqFt === null ? "—" : `${String(snapshot.plotAreaSqFt)} sq ft`} />
        <Line label="Plinth area" value={snapshot.plinthAreaSqFt === null ? "—" : `${String(snapshot.plinthAreaSqFt)} sq ft`} />
        <Line label="Built-up floors" value={String(areas.builtUpFloorCount)} />
        <Line label="Total built-up area" value={record.floors.length ? `${areas.builtUpSqFt} sq ft` : "—"} />
        <Line label="Open land area" value={areas.openLandFloorCount ? `${areas.openLandSqFt} sq ft` : "—"} />
        <Line label="Total open land area" value={areas.openLandFloorCount ? `${areas.openLandSqFt} sq ft` : "—"} />
      </ReviewCard>
      <ReviewCard title="Floors" onEdit={edit ? () => edit("area") : undefined}>
        {record.floors.length === 0 ? <Line label="Floors" value="—" /> : null}
        {record.floors.map((floor) => (
          <Line
            key={floor.id}
            label={optionLabel(floor.floorPosition)}
            value={`${optionLabel(floor.usageFactor)} · ${floor.usageType ? optionLabel(floor.usageType) : "—"} · ${optionLabel(floor.constructionType)} · ${floor.areaSqFt === null ? "—" : `${String(floor.areaSqFt)} sq ft`}`}
          />
        ))}
      </ReviewCard>
      <ReviewCard title="Services" onEdit={edit ? () => edit("services") : undefined}>
        <Line label="Water connection" value={labeled(snapshot.waterConnection)} />
        <Line label="Source of water" value={labeled(snapshot.sourceOfWater)} />
        <Line label="Sanitation" value={labeled(snapshot.sanitationType)} />
        <Line label="Door-to-door collection" value={display(snapshot.solidWasteCollection)} />
      </ReviewCard>
      <ReviewCard title="GPS" onEdit={edit ? () => edit("gps") : undefined}>
        {lat !== null && lng !== null ? <SurveyLocationMap latitude={lat} longitude={lng} /> : null}
        <Line label="Latitude" value={lat !== null ? lat.toFixed(6) : "—"} />
        <Line label="Longitude" value={lng !== null ? lng.toFixed(6) : "—"} />
        <Line label="Accuracy" value={accuracy !== null ? `${accuracy.toFixed(2)} m` : "—"} />
        <Line label="Captured" value={snapshot.capturedAt ? new Date(snapshot.capturedAt).toLocaleString() : "—"} />
        {freshness ? (
          <Text variant="caption" tone="danger">
            {freshness}
          </Text>
        ) : null}
      </ReviewCard>
      <ReviewCard title="Photos" onEdit={edit ? () => edit("photos") : undefined}>
        <Line label="Required photos" value={`${Number(hasFront) + Number(hasSide)}/2`} />
        <Line label="Front view" value={hasFront ? "Added" : "Required"} />
        <Line label="Side view" value={hasSide ? "Added" : "Required"} />
        <Line label="Inside view" value={hasInside ? "Added" : "Optional"} />
        <Line label="Document" value={hasDocument ? "Added" : "Optional"} />
      </ReviewCard>
    </View>
  )
}

function ReviewCard({
  title,
  onEdit,
  children,
}: {
  title: string
  onEdit?: () => void
  children: ReactNode
}) {
  return (
    <View style={[cardStyle, styles.card]}>
      <View style={styles.cardHeader}>
        <Text variant="label">{title}</Text>
        {onEdit ? (
          <Pressable accessibilityRole="button" accessibilityLabel={`Edit ${title}`} onPress={onEdit} hitSlop={8}>
            <Text variant="label" tone="primary">
              Edit
            </Text>
          </Pressable>
        ) : null}
      </View>
      {children}
    </View>
  )
}

function Line({ label, value }: { label: string; value: string }) {
  return (
    <View style={styles.line}>
      <Text variant="caption" tone="secondary">
        {label}
      </Text>
      <Text variant="bodyStrong">{value}</Text>
    </View>
  )
}

const styles = StyleSheet.create({
  stack: { gap: spacing.md, marginBottom: spacing.lg },
  card: { gap: spacing.sm },
  cardHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  line: {
    gap: 2,
    paddingVertical: spacing.xs,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: colors.border,
  },
})
