import { Text } from "@/components/ui"
import { areaMeasurePatch, summarizeAreas } from "../lib/area-summary"
import { displayPropertyId, propertyIdPreview } from "../lib/property-identity"
import { relationshipOptions } from "../lib/relationships"
import type { StepId, StepProgress } from "../lib/requirements"
import { STEP_TITLES } from "../lib/requirements"
import {
  OWNERSHIP_TYPES,
  PROPERTY_TYPES,
  PROPERTY_USES,
  ROAD_TYPES,
  SANITATION_TYPES,
  SITUATIONS,
  SOURCES_OF_WATER,
  TAX_RATE_ZONES,
  type DecimalWire,
  type SurveyEditableFields,
  type SurveyPatch,
  type SurveyRecord,
} from "../types"
import { AddressPinField } from "./address-pin-field"
import { AssessmentYearField } from "./assessment-year-field"
import { FloorsEditor } from "./ChildEditors"
import { GpsStep } from "./GpsStep"
import { NativeYesNoField } from "./NativeYesNoField"
import { OwnersEditor } from "./owners-editor"
import { PhotosStep } from "./PhotosStep"
import { BoundNumberField, BoundTextField, SectionCard } from "./primitives"
import { PropertyStep } from "./property-step"
import { StartStep } from "./start-step"
import { CatalogSelect, EnumSelect, SurveySelect } from "./SurveySelect"
import { WaterConnectionField } from "./water-connection-field"

type TextKey =
  | "parcelNumber"
  | "unitSubNo"
  | "propertyIdOld"
  | "respondentName"
  | "mobileNumber"
  | "alternateMobile"
  | "houseDoorNo"
  | "locality"
  | "colony"
  | "city"

function toNumber(value: DecimalWire): number | null {
  if (value === null) return null
  const n = typeof value === "number" ? value : Number(value)
  return Number.isFinite(n) ? n : null
}

type Props = {
  step: StepId
  record: SurveyRecord
  fields: SurveyEditableFields
  progress: StepProgress
  editable: boolean
  canPickWard: boolean
  setFields: (patch: SurveyPatch, options?: { immediate?: boolean }) => void
}

export function SurveyStepBody({ step, record, fields, progress, editable, canPickWard, setFields }: Props) {
  const identity = propertyIdPreview({
    ulbCode: record.ulbCode ?? record.ulb?.code,
    wardNo: record.ward?.wardNumber,
    currentWard: record.ward,
    originalWard: record.originalWard,
    storedWardNumber: record.wardNumber,
    parcelNo: fields.parcelNumber,
    unitNo: fields.unitSubNo,
    propertyUse: fields.propertyUse,
  })
  const propertyIdLabel = displayPropertyId(identity)
  const areas = summarizeAreas(fields.propertyUse, record.floors)

  const setText = (key: TextKey, text: string) => {
    const patch: SurveyPatch = {}
    const trimmed = text.trim()
    patch[key] = trimmed === "" ? null : trimmed
    setFields(patch)
  }
  const text = (
    key: TextKey,
    label: string,
    extra?: {
      keyboard?: "phone-pad" | "number-pad"
      max?: number
      caps?: "words" | "characters"
      error?: string
      required?: boolean
    },
  ) => (
    <BoundTextField
      label={label}
      required={extra?.required}
      value={fields[key]}
      editable={editable}
      keyboardType={extra?.keyboard}
      maxLength={extra?.max}
      autoCapitalize={extra?.caps ?? "none"}
      error={extra?.error}
      onCommit={(t) => setText(key, t)}
    />
  )

  switch (step) {
    case "start":
      return (
        <SectionCard title={STEP_TITLES.start} progress={progress}>
          <StartStep
            record={record}
            fields={fields}
            editable={editable}
            canPickWard={canPickWard}
            propertyIdLabel={propertyIdLabel}
            propertyIdHint={
              identity.isComplete
                ? "Generated by the server. Read-only."
                : identity.value
                  ? "Base ID. The property-use letter is added on the taxation step."
                  : "Property ID is assigned by the server. It cannot be edited."
            }
            setFields={setFields}
          />
        </SectionCard>
      )
    case "property":
      return (
        <SectionCard title={STEP_TITLES.property} progress={progress}>
          <PropertyStep record={record} fields={fields} editable={editable} setFields={setFields} />
        </SectionCard>
      )
    case "owner":
      return (
        <SectionCard title={STEP_TITLES.owner} progress={progress}>
          <Text variant="label">Respondent</Text>
          {text("respondentName", "Name of respondent", { caps: "words" })}
          <SurveySelect
            label="Respondent relationship with owner"
            required
            value={fields.relationshipWithOwner}
            disabled={!editable}
            placeholder="Select relationship"
            options={relationshipOptions(fields.relationshipWithOwner)}
            error={fields.relationshipWithOwner?.trim() ? undefined : "Relationship with owner is required."}
            onChange={(relationshipWithOwner) => setFields({ relationshipWithOwner })}
          />
          <OwnersEditor
            surveyId={record.id}
            coOwners={record.coOwners}
            editable={editable}
            onPrimaryContact={(patch) => {
              if (fields.mobileNumber === patch.mobileNumber && fields.alternateMobile === patch.alternateMobile) return
              setFields(patch)
            }}
          />
          <Text variant="label">Household</Text>
          <BoundNumberField
            label="Number of family members"
            integer
            value={fields.familySize}
            editable={editable}
            onCommit={(v) => setFields({ familySize: v })}
          />
        </SectionCard>
      )
    case "address":
      return (
        <SectionCard title={STEP_TITLES.address} progress={progress}>
          <Field label="District" value={record.district?.name ?? "—"} />
          <Field label="City / Town (ULB)" value={record.ulb?.name ?? "—"} />
          <Text variant="caption" tone="secondary">
            District and city come from the survey assignment and cannot be changed here.
          </Text>
          {text("houseDoorNo", "House number")}
          {text("locality", "Locality", { caps: "words" })}
          {text("colony", "Colony", { caps: "words" })}
          <AddressPinField ulbId={record.ulbId} pinCode={fields.pinCode} editable={editable} setFields={setFields} />
        </SectionCard>
      )
    case "taxation":
      return (
        <SectionCard title={STEP_TITLES.taxation} progress={progress}>
          <CatalogSelect
            category="OWNERSHIP_TYPE"
            allowed={OWNERSHIP_TYPES}
            label="Ownership type"
            required
            value={fields.ownershipType}
            disabled={!editable}
            onChange={(v) => setFields({ ownershipType: v })}
          />
          <CatalogSelect
            category="PROPERTY_USE"
            allowed={PROPERTY_USES}
            label="Property use"
            required
            value={fields.propertyUse}
            disabled={!editable}
            onChange={(v) => setFields({ propertyUse: v })}
          />
          <CatalogSelect
            category="PROPERTY_TYPE"
            allowed={PROPERTY_TYPES}
            label="Property type"
            required
            value={fields.propertyType}
            disabled={!editable}
            onChange={(v) => setFields({ propertyType: v })}
          />
          <Text variant="caption" tone="secondary">
            {identity.isComplete
              ? `Property ID ${identity.value}`
              : "Choosing property use adds the final letter to the Property ID."}
          </Text>
          <CatalogSelect
            category="SITUATION"
            allowed={SITUATIONS}
            label="Situation"
            value={fields.situation}
            disabled={!editable}
            onChange={(v) => setFields({ situation: v })}
          />
          <CatalogSelect
            category="ROAD_TYPE"
            allowed={ROAD_TYPES}
            label="Road type"
            value={fields.roadType}
            disabled={!editable}
            onChange={(v) => setFields({ roadType: v })}
          />
          <CatalogSelect
            category="TAX_RATE_ZONE"
            allowed={TAX_RATE_ZONES}
            label="Road size tax zone"
            value={fields.taxRateZone}
            disabled={!editable}
            onChange={(v) => setFields({ taxRateZone: v })}
          />
          <AssessmentYearField year={fields.assessmentYear} />
        </SectionCard>
      )
    case "area":
      return (
        <SectionCard title={STEP_TITLES.area} progress={progress}>
          <BoundNumberField
            label="Plot area (sq ft)"
            value={toNumber(fields.plotAreaSqFt)}
            editable={editable}
            onCommit={(v) => setFields(areaMeasurePatch("plot", v))}
          />
          <BoundNumberField
            label="Plinth area (sq ft)"
            value={toNumber(fields.plinthAreaSqFt)}
            editable={editable}
            onCommit={(v) => setFields(areaMeasurePatch("plinth", v))}
          />
          <Field label="Built-up floors" value={record.floors.length ? String(areas.builtUpFloorCount) : "—"} />
          <Field label="Total built-up area" value={formatSqFt(areas.builtUpSqFt, record.floors.length > 0)} />
          <Field label="Open land area" value={formatSqFt(areas.openLandSqFt, areas.openLandFloorCount > 0)} />
          <Field label="Total open land area" value={formatSqFt(areas.openLandSqFt, areas.openLandFloorCount > 0)} />
          <Text variant="caption" tone="secondary">
            Built-up and open land follow the server floor totals. Open land is the sum of open-land floor rows.
          </Text>
          <FloorsEditor surveyId={record.id} floors={record.floors} editable={editable} />
        </SectionCard>
      )
    case "services":
      return (
        <SectionCard title={STEP_TITLES.services} progress={progress}>
          <WaterConnectionField
            label="Municipal / Town Panchayat water connection"
            value={fields.waterConnection}
            disabled={!editable}
            onChange={(v) => setFields({ waterConnection: v })}
          />
          <EnumSelect
            label="Source of water"
            options={SOURCES_OF_WATER}
            value={fields.sourceOfWater}
            disabled={!editable}
            onChange={(v) => setFields({ sourceOfWater: v })}
          />
          <EnumSelect
            label="Sanitation"
            options={SANITATION_TYPES}
            value={fields.sanitationType}
            disabled={!editable}
            onChange={(v) => setFields({ sanitationType: v })}
          />
          <NativeYesNoField
            label="Municipal / Town Panchayat door-to-door solid waste collection"
            value={fields.solidWasteCollection}
            disabled={!editable}
            onChange={(v) => setFields({ solidWasteCollection: v })}
          />
        </SectionCard>
      )
    case "gps":
      return (
        <SectionCard title={STEP_TITLES.gps} progress={progress}>
          <GpsStep fields={fields} editable={editable} onCapture={(patch) => setFields(patch, { immediate: true })} />
        </SectionCard>
      )
    case "photos":
      return (
        <SectionCard title={STEP_TITLES.photos} progress={progress}>
          <PhotosStep surveyId={record.id} photos={record.photos} editable={editable} />
        </SectionCard>
      )
    case "review":
      return null
    default: {
      const exhaustive: never = step
      return exhaustive
    }
  }
}

function formatSqFt(value: number, show: boolean): string {
  if (!show) return "—"
  return `${String(value)} sq ft`
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <>
      <Text variant="label" tone="secondary">
        {label}
      </Text>
      <Text variant="bodyStrong">{value}</Text>
    </>
  )
}
