import { Text } from "@/components/ui"
import { digitsOnly, parcelNumberError, phoneError, pinCodeError, unitNumberError } from "../lib/field-format"
import { previewPropertyId } from "../lib/property-identity"
import type { StepId, StepProgress, SurveySnapshot } from "../lib/requirements"
import { STEP_TITLES } from "../lib/requirements"
import {
  ASSESSMENT_YEARS,
  OWNERSHIP_TYPES,
  PROPERTY_TYPES,
  PROPERTY_USES,
  ROAD_TYPES,
  SANITATION_TYPES,
  SITUATIONS,
  SOURCES_OF_WATER,
  TAX_RATE_ZONES,
  WATER_CONNECTIONS,
  type DecimalWire,
  type SurveyEditableFields,
  type SurveyPatch,
  type SurveyRecord,
} from "../types"
import { CoOwnersEditor, FloorsEditor } from "./ChildEditors"
import { GpsStep } from "./GpsStep"
import { NativeYesNoField } from "./NativeYesNoField"
import { PhotosStep } from "./PhotosStep"
import { BoundNumberField, BoundTextField, SectionCard } from "./primitives"
import { CatalogSelect, EnumSelect } from "./SurveySelect"

type TextKey =
  | "parcelNumber"
  | "unitSubNo"
  | "propertyIdOld"
  | "respondentName"
  | "relationshipWithOwner"
  | "mobileNumber"
  | "alternateMobile"
  | "houseDoorNo"
  | "locality"
  | "colony"
  | "city"
  | "pinCode"

function toNumber(value: DecimalWire): number | null {
  if (value === null) return null
  const n = typeof value === "number" ? value : Number(value)
  return Number.isFinite(n) ? n : null
}

type Props = {
  step: StepId
  record: SurveyRecord
  fields: SurveyEditableFields
  snapshot: SurveySnapshot
  progress: StepProgress
  editable: boolean
  setFields: (patch: SurveyPatch, options?: { immediate?: boolean }) => void
}

export function SurveyStepBody({ step, record, fields, snapshot, progress, editable, setFields }: Props) {
  const identityPreview = previewPropertyId({
    ulbCode: record.ulbCode ?? record.ulb?.code,
    wardNo: record.ward?.wardNumber,
    currentWard: record.ward,
    originalWard: record.originalWard,
    storedWardNumber: record.wardNumber,
    parcelNo: fields.parcelNumber,
    unitNo: fields.unitSubNo,
    propertyUse: fields.propertyUse,
  })
  const propertyIdLabel = (pendingCopy: string) => identityPreview ?? pendingCopy

  const setText = (key: TextKey, text: string) => {
    const patch: SurveyPatch = {}
    const trimmed = text.trim()
    patch[key] = trimmed === "" ? null : trimmed
    setFields(patch)
  }
  const text = (
    key: TextKey,
    label: string,
    extra?: {
      keyboard?: "phone-pad" | "number-pad"
      max?: number
      caps?: "words" | "characters"
      error?: string
      required?: boolean
    },
  ) => (
    <BoundTextField
      label={label}
      required={extra?.required}
      value={fields[key]}
      editable={editable}
      keyboardType={extra?.keyboard}
      maxLength={extra?.max}
      autoCapitalize={extra?.caps ?? "none"}
      error={extra?.error}
      onCommit={(t) => setText(key, t)}
    />
  )

  switch (step) {
    case "start":
      return (
        <SectionCard title={STEP_TITLES.start} progress={progress}>
          <Field label="Ward" value={snapshot.wardLabel ?? "—"} />
          <Field label="ULB" value={record.ulb?.name ?? "—"} />
          <Field
            label="Property ID"
            value={propertyIdLabel("Will be generated after parcel, unit and property use are completed.")}
          />
          <Text variant="caption" tone="secondary">
            {identityPreview ? "Generated by server. Read-only." : "Property ID is assigned by the server. It cannot be edited."}
          </Text>
        </SectionCard>
      )
    case "property":
      return (
        <SectionCard title={STEP_TITLES.property} progress={progress}>
          <BoundTextField
            label="Parcel number"
            required
            value={fields.parcelNumber}
            editable={editable}
            keyboardType="number-pad"
            error={parcelNumberError(fields.parcelNumber)}
            onCommit={(raw) => {
              const digits = digitsOnly(raw)
              setFields({ parcelNumber: digits === "" ? null : digits })
            }}
          />
          <BoundTextField
            label="Unit number"
            required
            value={fields.unitSubNo}
            editable={editable}
            keyboardType="number-pad"
            error={unitNumberError(fields.unitSubNo)}
            onCommit={(raw) => {
              const digits = digitsOnly(raw)
              setFields({ unitSubNo: digits === "" ? null : digits })
            }}
          />
          {text("propertyIdOld", "Old property ID", { caps: "characters" })}
          <Field
            label="Property ID"
            value={propertyIdLabel("Will be generated after parcel, unit and property use are completed.")}
          />
          <Text variant="caption" tone="secondary">
            {identityPreview ? "Generated by server. Read-only." : "Complete parcel, unit and property use to generate the id."}
          </Text>
          <CatalogSelect
            category="OWNERSHIP_TYPE"
            allowed={OWNERSHIP_TYPES}
            label="Ownership type"
            required
            value={fields.ownershipType}
            disabled={!editable}
            onChange={(v) => setFields({ ownershipType: v })}
          />
          <CatalogSelect
            category="PROPERTY_USE"
            allowed={PROPERTY_USES}
            label="Property use"
            required
            value={fields.propertyUse}
            disabled={!editable}
            onChange={(v) => setFields({ propertyUse: v })}
          />
          <CatalogSelect
            category="PROPERTY_TYPE"
            allowed={PROPERTY_TYPES}
            label="Property type"
            required
            value={fields.propertyType}
            disabled={!editable}
            onChange={(v) => setFields({ propertyType: v })}
          />
        </SectionCard>
      )
    case "owner":
      return (
        <SectionCard title={STEP_TITLES.owner} progress={progress}>
          {text("respondentName", "Owner / Respondent name", { caps: "words" })}
          {text("relationshipWithOwner", "Relationship with owner", {
            caps: "words",
            required: true,
            error: fields.relationshipWithOwner?.trim() ? undefined : "Relationship with owner is required.",
          })}
          {text("mobileNumber", "Mobile number", {
            keyboard: "phone-pad",
            max: 15,
            error: phoneError(fields.mobileNumber),
          })}
          {text("alternateMobile", "Alternate mobile", {
            keyboard: "phone-pad",
            max: 15,
            error: phoneError(fields.alternateMobile),
          })}
          <BoundNumberField
            label="Family size"
            integer
            value={fields.familySize}
            editable={editable}
            onCommit={(v) => setFields({ familySize: v })}
          />
          <CoOwnersEditor
            surveyId={record.id}
            coOwners={record.coOwners}
            editable={editable}
            required={fields.ownershipType === "JOINT"}
          />
        </SectionCard>
      )
    case "address":
      return (
        <SectionCard title={STEP_TITLES.address} progress={progress}>
          {text("houseDoorNo", "House / Door no.")}
          {text("locality", "Locality", { caps: "words" })}
          {text("colony", "Colony", { caps: "words" })}
          {text("city", "City", { caps: "words" })}
          {text("pinCode", "PIN code", {
            keyboard: "number-pad",
            max: 6,
            error: pinCodeError(fields.pinCode),
          })}
        </SectionCard>
      )
    case "taxation":
      return (
        <SectionCard title={STEP_TITLES.taxation} progress={progress}>
          <CatalogSelect
            category="SITUATION"
            allowed={SITUATIONS}
            label="Situation"
            value={fields.situation}
            disabled={!editable}
            onChange={(v) => setFields({ situation: v })}
          />
          <CatalogSelect
            category="ROAD_TYPE"
            allowed={ROAD_TYPES}
            label="Road type"
            value={fields.roadType}
            disabled={!editable}
            onChange={(v) => setFields({ roadType: v })}
          />
          <CatalogSelect
            category="TAX_RATE_ZONE"
            allowed={TAX_RATE_ZONES}
            label="Road size tax zone"
            value={fields.taxRateZone}
            disabled={!editable}
            onChange={(v) => setFields({ taxRateZone: v })}
          />
          <CatalogSelect
            category="ASSESSMENT_YEAR"
            allowed={ASSESSMENT_YEARS}
            label="Assessment year"
            required
            value={fields.assessmentYear}
            disabled={!editable}
            onChange={(v) => {
              if (v) setFields({ assessmentYear: v })
            }}
          />
        </SectionCard>
      )
    case "area":
      return (
        <SectionCard title={STEP_TITLES.area} progress={progress}>
          <BoundNumberField
            label="Plot area (sq ft)"
            value={toNumber(fields.plotAreaSqFt)}
            editable={editable}
            onCommit={(v) => setFields({ plotAreaSqFt: v })}
          />
          <BoundNumberField
            label="Plinth area (sq ft)"
            value={toNumber(fields.plinthAreaSqFt)}
            editable={editable}
            onCommit={(v) => setFields({ plinthAreaSqFt: v })}
          />
          <Field
            label="Total built-up area"
            value={
              record.floors.length
                ? `${record.floors.reduce((sum, floor) => sum + (toNumber(floor.areaSqFt) ?? 0), 0)} sq ft`
                : "—"
            }
          />
          <Text variant="caption" tone="secondary">
            Built-up area is the sum of floor areas. Open land is recorded as an open-land floor or property use.
            This survey has no separate open-land area column.
          </Text>
          <FloorsEditor surveyId={record.id} floors={record.floors} editable={editable} />
        </SectionCard>
      )
    case "services":
      return (
        <SectionCard title={STEP_TITLES.services} progress={progress}>
          <EnumSelect
            label="Municipal / Town Panchayat water connection"
            options={WATER_CONNECTIONS}
            value={fields.waterConnection}
            disabled={!editable}
            onChange={(v) => setFields({ waterConnection: v })}
          />
          <EnumSelect
            label="Source of water"
            options={SOURCES_OF_WATER}
            value={fields.sourceOfWater}
            disabled={!editable}
            onChange={(v) => setFields({ sourceOfWater: v })}
          />
          <EnumSelect
            label="Sanitation"
            options={SANITATION_TYPES}
            value={fields.sanitationType}
            disabled={!editable}
            onChange={(v) => setFields({ sanitationType: v })}
          />
          <NativeYesNoField
            label="Solid waste collection (door-to-door)"
            value={fields.solidWasteCollection}
            disabled={!editable}
            onChange={(v) => setFields({ solidWasteCollection: v })}
          />
        </SectionCard>
      )
    case "gps":
      return (
        <SectionCard title={STEP_TITLES.gps} progress={progress}>
          <GpsStep fields={fields} editable={editable} onCapture={(patch) => setFields(patch, { immediate: true })} />
        </SectionCard>
      )
    case "photos":
      return (
        <SectionCard title={STEP_TITLES.photos} progress={progress}>
          <PhotosStep surveyId={record.id} photos={record.photos} editable={editable} />
        </SectionCard>
      )
    default: {
      const exhaustive: never = step
      return exhaustive
    }
  }
}

function Field({ label, value }: { label: string; value: string }) {
  return (
    <>
      <Text variant="label" tone="secondary">
        {label}
      </Text>
      <Text variant="bodyStrong">{value}</Text>
    </>
  )
}
